name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        TAG_NAME="${{ github.ref_name }}"
        docker build . --file Dockerfile --tag btsomogyi/claude-flow-container:$(date +%s) --tag btsomogyi/claude-flow-container:${TAG_NAME}
