name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CLAUDE_FLOW_ALPHA_VERSION: "89"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run:  cd docker && docker build . --build-arg CF_ALPHA_VERSION=$CLAUDE_FLOW_ALPHA_VERSION --file Dockerfile --tag btsomogyi/claude-flow-container:$CLAUDE_FLOW_ALPHA_VERSION-$(date +%s)
